### ISSUE TITLE
Customized JIRA fields

### ISSUE THREAD

**Issue by jerbia** [aquasecurity/alm-integration#7]
We would like to following fields to be configured via the cfg.yaml: 

Project-Key 
Board 
Issue-Type 
Priority 
Jira-Labels=<list of JIRA labels to add to the ticket> 
Assignee 
 
unknowns: <optional custom fields>
     custom-field: <value> e.g., hello world
     custom-field-numeric-field: 1337
     custom-field-multiple-value: <value1>, <value2> e.g., 1,2,3 (must be separated by commas)
     custom-field-multiple-line-text-field: "text \n moretext" (quotes are mandatory for this field)
     custom-field-date-time-picker: <date && time> e.g., 2014-04-11T12:14:26.880+0400
     custom-field-url: <url> e.g., https://tour.golang.org/moretypes/7

**Comment by afdesk** [comment]
@jerbia I transferred my questions to this ticket.

There are a few moments:
1. Can we use a `projectKey` instead of `project id`? I think that `Project id` is Jira's inner data.

2. What is mean a `project name`? Now it uses as project key. There is an error if `project name` doesn't match `project id`

3. `IsuueType` is empty, but issue type is required. It should set up, or need default value. `Bug`?

4. Now `priority` and `assignee` are required params. Is it correct? Maybe I need default values?
`High` and current user?

5. Actions with `description` param. What I have to do with it? this param overlays rendered data. is it correct?

**Comment by jerbia** [comment]
1. Yes. Let's remove the project ID from the configuration file.
2. Let's remove Project Name and just use Project Key
3. Let's put "Bug" as default value.
4. Yes, default values will be good.
5. Description can be removed. 

Basically can you check that all the fields are easy to get from JIRA UI and that we don't have something that requires an internal ID?

**Comment by jerbia** [comment]
@afdesk I've updated the issue details. Seems like there is already support to custom fields in the cfg.yaml. Can you please test that it is working?

custom: <optional custom fields>
     custom-field: <value> e.g., hello world
     custom-field-numeric-field: 1337
     custom-field-multiple-value: <value1>, <value2> e.g., 1,2,3 (must be separated by commas)
     custom-field-multiple-line-text-field: "text \n moretext" (quotes are mandatory for this field)
     custom-field-date-time-picker: <date && time> e.g., 2014-04-11T12:14:26.880+0400
     custom-field-url: <url> e.g., https://tour.golang.org/moretypes/7

**Comment by jerbia** [comment]
OK, I've checked the "unknown" and it seems to work (custom fields are created).

Please merge the pull request with master and I will approve it.

**Comment by jerbia** [comment]
#15
